name: Vet & Test

on: 
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v5.0.0
      with:
        go-version-file: "go.mod"

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet -v ./...

    - name: Test
      run: go test -v ./...
