name: Vet & Test

on: 
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout SchopYatch
      uses: actions/checkout@v6.0.2

    - name: Checkout Godave
      uses: actions/checkout@v6.0.2
      with:
        repository: disgoorg/godave
        path: godave

    - name: Compile DAVE
      run: |
        cd ~/godave/scripts
        chmod +x libdave_install.sh
        NON_INTERACTIVE=1 ./libdave_install.sh v1.1.1

    - name: Set up Go
      uses: actions/setup-go@v6.4.0
      with:
        go-version-file: "go.mod"

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet -v ./...

    - name: Test
      run: go test -v ./...
