name: Build And Test SchopYatch

on: [push, pull_request]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4.0.1
      with:
        go-version-file: "go.mod"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
