# Ensures SchopYatch is properly tested before
# ultimately deployed to production.
name: Deploy SchopYatch

on: 
  push: 
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Check Build
    uses: Schoperation/SchopYatch/.github/workflows/build_and_test.yml@master
  deploy:
    name: Deploy To Server
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/SchopYatch
            git pull
            rm schopyatch
            pkill schopyatch
            /usr/local/go/bin/go build .
            cp schopyatch ../../schopyatch_bot/
            cd ../../schopyatch_bot
            ./schopyatch &>logs/schopyatch.log &
